language: swift
osx_image: xcode8.3
xcode_workspace: FlipConnectSDKWorkspace.xcworkspace
xcode_scheme: FlipConnectSDK
env:
  global:
    - FRAMEWORK_NAME=FlipConnectSDK
before_install:
  - brew update
  - brew outdated carthage || brew upgrade carthage
  - gem install bundler
  - bundle install
script:
  - carthage build --no-skip-current
  - carthage archive $FRAMEWORK_NAME
  - bundle exec fastlane travis
after_success:
  - bash <(curl -s https://codecov.io/bash)