COMMIT_MESSAGE = "New version:"

lane :tests do
  scan(workspace: "FlipConnectSDKWorkspace.xcworkspace", scheme: "FlipConnectSDK", clean: true)
end

lane :travis do
  tests
end

lane :bitrise do
  tests
  push
end

lane :push do
  sh("git fetch --tags")
  tag = last_git_tag
  version = version_bump_podspec(path: "FlipConnectSDK.podspec", version_number: tag)
  git_commit(path: ["./FlipConnectSDK.podspec"], message: "#{COMMIT_MESSAGE} #{version}")
  #changelog = changelog_from_git_commits
  #github_release = set_github_release(
  #  repository_name: "Flip-Payments/connect-sdk-ios",
  #  api_token: ENV['GITHUB_TOKEN'],
  #  name: version,
  #  tag_name: version,
  #  description: changelog,
  #  commitish: "master"
  #)
  push_to_git_remote(remote_branch: 'master', force: false, tags: true)
  pod_push(path: "FlipConnectSDK.podspec" , allow_warnings: true, verbose: true)
end