COMMIT_MESSAGE = "New version:"

lane :tests do
  scan(workspace: "FlipConnectSDKWorkspace.xcworkspace", scheme: "FlipConnectSDK", clean: true)
end

lane :travis do
  tests
end

lane :bitrise do
  tests
  jazzy
  changelog
  push
end

lane :changelog do
  changelog = generate_changelog(
    github_project: 'Flip-Payments/connect-sdk-ios',
    github_api_token: 'GITHUB_API_TOKEN',
    base_branch: 'master',
    template_path: 'fastlane/changelog_template.erb',
    include_unreleased_section: true, # Optional, defaults to false
    output_path: 'CHANGELOG.md' # Optional
  )
end

lane :push do
  sh("git fetch --tags")
  tag = last_git_tag
  version = version_bump_podspec(path: "FlipConnectSDK.podspec", version_number: tag)
  git_commit(path: ["./FlipConnectSDK.podspec"], message: "#{COMMIT_MESSAGE} #{version}")
  git_commit(path: ["./docs/"], message: "Updates documention for version #{version}")
  git_commit(path: ["./CHANGELOG.md"], message: "Updates changelog for version #{version}")
  push_to_git_remote(remote_branch: 'master', force: false, tags: true)
  pod_push(path: "FlipConnectSDK.podspec" , allow_warnings: true, verbose: true)
end